name: exchange_language_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  comment_tree: ^0.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_image_compress: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^5.0.3
  flutter_spinkit: ^5.1.0
  hive: ^2.1.0
  http_parser: ^4.0.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  path_provider: ^2.0.9
  retrofit: ^3.0.1+1
  settings_ui: ^2.0.2
  shimmer: ^2.0.0
  sizer: ^2.0.15
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  translator: ^0.1.7

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
#flutter packages pub run build_runner build --delete-conflicting-outputs
